# Generated by Django 5.0.2 on 2024-03-07 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminpanel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="expiration_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
