# Generated by Django 5.0.2 on 2024-02-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_photographerprofile_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photographerprofile",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
    ]
