# Generated by Django 5.0.2 on 2024-02-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_alter_photographerprofile_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photographerprofile",
            name="specialty",
            field=models.CharField(
                choices=[
                    ("portrait", "Portrait Photography"),
                    ("landscape", "Landscape Photography"),
                    ("wedding Photography", "Wedding Photography"),
                    ("wildlife", "Wildlife Photography"),
                    ("fashion", "Fashion Photography"),
                    ("sports", "Sports Photography"),
                    ("macro", "Macro Photography"),
                    ("architectural", "Architectural Photography"),
                    ("event", "Event Photography"),
                    ("product", "Product Photography"),
                    ("food", "Food Photography"),
                    ("street", "Street Photography"),
                ],
                max_length=20,
            ),
        ),
    ]
