# Generated by Django 5.0.2 on 2024-11-20 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_alter_user_otp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="otp",
            field=models.CharField(max_length=4, null=True),
        ),
    ]
