# Generated by Django 5.0.2 on 2024-03-01 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("follow", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="follow",
            name="create_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 3, 1, 16, 29, 53, 591969)
            ),
        ),
    ]
