# Generated by Django 5.0.2 on 2024-02-25 09:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("follow", "0019_alter_follow_create_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="follow",
            name="create_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 2, 25, 15, 24, 46, 502147)
            ),
        ),
    ]
