# Generated by Django 5.0.2 on 2024-03-01 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="username",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
