# Generated by Django 5.0 on 2024-01-22 10:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_bookingphotographer_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingphotographer',
            name='booking_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 22, 15, 55, 42, 200085)),
        ),
    ]
