# Generated by Django 5.0.2 on 2024-11-20 06:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0005_alter_bookingphotographer_booking_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingphotographer",
            name="booking_date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 11, 20, 11, 42, 46, 73803)
            ),
        ),
    ]
