# Generated by Django 5.0 on 2024-02-13 05:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0006_alter_bookingphotographer_booking_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingphotographer",
            name="booking_date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 2, 13, 10, 42, 19, 980221)
            ),
        ),
    ]
