# Generated by Django 5.0.2 on 2024-02-27 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0015_remove_bookingphotographer_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingphotographer",
            name="booking_date",
            field=models.DateTimeField(),
        ),
    ]
