# Generated by Django 5.0.2 on 2024-02-27 04:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0016_alter_bookingphotographer_booking_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingphotographer",
            name="booking_date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 2, 27, 10, 16, 36, 796200)
            ),
        ),
    ]
