# Generated by Django 5.0.2 on 2024-11-20 06:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0004_alter_comment_created_at_alter_like_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 11, 20, 11, 42, 46, 15761)
            ),
        ),
        migrations.AlterField(
            model_name="like",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 11, 20, 11, 42, 46, 15761)
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 11, 20, 11, 42, 46, 15761)
            ),
        ),
        migrations.AlterField(
            model_name="posthistory",
            name="deleted_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 11, 20, 11, 42, 46, 24026)
            ),
        ),
    ]
