# Generated by Django 5.0 on 2024-01-16 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0006_posthistory_comment_posthistory_like_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="posthistory",
            name="comment",
        ),
        migrations.RemoveField(
            model_name="posthistory",
            name="like",
        ),
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 16, 19, 30, 51, 336267)
            ),
        ),
        migrations.AlterField(
            model_name="posthistory",
            name="deleted_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 16, 19, 30, 51, 336267)
            ),
        ),
    ]
