# Generated by Django 5.0 on 2024-01-16 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0015_alter_post_created_at_alter_posthistory_deleted_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 16, 23, 16, 37, 910721)
            ),
        ),
        migrations.AlterField(
            model_name="posthistory",
            name="deleted_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 16, 23, 16, 37, 910721)
            ),
        ),
    ]
