# Generated by Django 5.0 on 2024-01-17 00:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0016_alter_post_created_at_alter_posthistory_deleted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posthistory',
            name='post',
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 17, 6, 18, 40, 36000)),
        ),
        migrations.AlterField(
            model_name='posthistory',
            name='deleted_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 17, 6, 18, 40, 36000)),
        ),
    ]
