# Generated by Django 5.0 on 2024-01-18 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0018_alter_post_created_at_alter_posthistory_deleted_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 18, 23, 26, 10, 697518)
            ),
        ),
        migrations.AlterField(
            model_name="like",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 18, 23, 26, 10, 697518)
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 18, 23, 26, 10, 697518)
            ),
        ),
        migrations.AlterField(
            model_name="posthistory",
            name="deleted_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 18, 23, 26, 10, 697518)
            ),
        ),
    ]
