# Generated by Django 5.0 on 2024-01-20 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0021_wishlist_user_alter_comment_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 20, 17, 36, 47, 160284)
            ),
        ),
        migrations.AlterField(
            model_name="like",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 20, 17, 36, 47, 160284)
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 20, 17, 36, 47, 160284)
            ),
        ),
        migrations.AlterField(
            model_name="posthistory",
            name="deleted_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 20, 17, 36, 47, 160284)
            ),
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="create_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 20, 17, 36, 47, 160284)
            ),
        ),
    ]
