# Generated by Django 5.0 on 2024-02-10 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0028_alter_comment_created_at_alter_comment_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 10, 16, 15, 31, 807565)),
        ),
        migrations.AlterField(
            model_name='like',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 10, 16, 15, 31, 807565)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 10, 16, 15, 31, 806567)),
        ),
        migrations.AlterField(
            model_name='posthistory',
            name='deleted_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 10, 16, 15, 31, 807565)),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 10, 16, 15, 31, 807565)),
        ),
    ]
